language: python
sudo: required

python:
    - '2.7'

env:
    matrix:
        # Django 1.6
        - COMBO="Django==1.6.8 South==1.0.1 django-oscar==1.0"
        # Django 1.7
        - COMBO="Django==1.7.1 django-oscar==1.0"

matrix:
    include:
        - python: '3.3'
          env: COMBO="Django==1.6.8 South==1.0.1 django-oscar==1.0"
        - python: '3.3'
          env: COMBO="Django==1.7.1 django-oscar==1.0"
        - python: '3.4'
          env: COMBO="Django==1.6.8 South==1.0.1 django-oscar==1.0"
        - python: '3.4'
          env: COMBO="Django==1.7.1 django-oscar==1.0"

install:
    - pip install $COMBO -r requirements.txt -e .

script:
    - python ./runtests.py

#after_success:
#    - coveralls
